### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by cb-heimdall** [coinbase/redisbetween#20]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/redisbetween/compare/a1acb833779912aebcac28184ec031ad1188ea2c...441d402a141aedfa0180638fc1cb26e692d9061e) was merged to master by jeffsaremi.

Comment with appropriate number of :+1: to approve.

---

Reviewed requirements satisfied? No
Ancestors reviewed? Yes

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/redisbetween&ref=7a0f09b8ce35ebae89c1d2480421b726924c4b51)

**Comment by d2army** [comment]
👍

**Comment by cb-heimdall** [comment]
Review Error for d2army @ 2023-04-05 17:27:24 UTC
User failed mfa authentication, public email is not set on your github profile. see [go/mfa-help](http://go/mfa-help)

**Comment by d2army** [comment]
👍

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 1/1
------------ | -------------
d2army | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/redisbetween&ref=7a0f09b8ce35ebae89c1d2480421b726924c4b51)
