### ISSUE TITLE
Unreviewed commit on master!

### ISSUE THREAD

**Issue by cb-heimdall** [coinbase/redisbetween#9]
Unreviewed commit(s) [COMPARE](https://github.com/coinbase/redisbetween/compare/f8c5cbf64a2f6e7868119db50b9abe9010988888...f634a33c3c44fc57b2885f9d6dfa35ff9d64b278) was merged to master by mbeasley.

Comment with appropriate number of :+1: to approve.

---

Reviewed requirements satisfied? No
Ancestors reviewed? Yes

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 0/1
------------ | -------------






[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/redisbetween&ref=106a86be587a987e56fdc316622d551e322b56fd)

**Comment by mdehoog** [comment]
+1

**Comment by cb-heimdall** [comment]
Minimum Reviews      | 1/1
------------ | -------------
mdehoog | 1



Pull request is reviewed and can be merged to master!

[More info](https://heimdall-public.cbhq.net/v1/code_change?repository=coinbase/redisbetween&ref=106a86be587a987e56fdc316622d551e322b56fd)
